### ISSUE TITLE
Add to dictionary from command line

### ISSUE THREAD

**Issue by pbogut** [myint/scspell#19]
First of all, nice tool, thanks for doing that.

Is there a way to add a word to dictionary from command line (without interactive mode)?

I'm using this as a linter checker. It works great, however, when I'm in Vim I can't (actually I could but I don't want to) use it in interactive mode. But I still would like to have a way to add a word to dictionary. So something like `scspell --add-to-natural-dictionary myfancyword` would be great.

**Comment by pbogut** [comment]
Would you accept PR if I implement this feature? I'm fancy doing that.

If so, which version would you prefer?
  - One argument per dictionary:
    - `--add-to-natural-dict WORD`
    - `--add-to-programing-dict {EXTENTION|NAME|FILE} WORD`
    - `--add-to-file-dict FILE WORD`
  - One argument with different parameters:
    - `--add-to-dict DICT_TYPE [EXTENTION|NAME|FILE] WORD`

Or maybe even different approach?

**Comment by myint** [comment]
Sure, I'll accept a pull request. The latter approach with varying parameters seems preferable to avoid clutter.
